/* 礼包码数据 - 每天更新这个文件即可 */
const GIFT_CODES = [
  {
    group: "2026-09-23 更新",
    codes: [
      { code: "WYHCS5PU", reward: "通用礼包", date: "2026-09-23" },
      { code: "yxz787DU5R", reward: "通用礼包", date: "2026-09-23" },
      { code: "xyxz40w666", reward: "通用礼包", date: "2026-09-22" },
      { code: "中秋企微专属礼", reward: "通用礼包", date: "2026-09-22" },
      { code: "YXZER87H", reward: "通用礼包", date: "2026-09-22" },
      { code: "游戏圈生存补给", reward: "通用礼包", date: "2026-09-22" },
      { code: "益起过中秋", reward: "通用礼包", date: "2026-09-21" },
      { code: "xyxz40w666", reward: "通用礼包", date: "2026-09-20" },
      { code: "VXY2CKO2", reward: "藏品劵×2、原料自选包×8000、加速器×600", date: "2026-09-19" },
      { code: "5JDWTSDJ", reward: "藏品劵×2、原料自选包×8000、加速器×600", date: "2026-09-19" },
      { code: "SSJ8Z3X", reward: "稀有装备材料自选×40、强化石×2000、加速器×200", date: "2026-09-19" },
      { code: "18SJJ53", reward: "稀有装备材料自选×40、强化石×2000、加速器×200", date: "2026-09-19" },
      { code: "X5SSJ9", reward: "招募卡×2、原料自选包×4000、加速器×200", date: "2026-09-19" },
      { code: "9SSJ2N", reward: "招募卡×2、原料自选包×4000、加速器×200", date: "2026-09-19" },
      { code: "BSSJ4F", reward: "招募卡×2、原料自选包×4000、加速器×200", date: "2026-09-19" },
      { code: "JUEUN777", reward: "珠珠专属新手好礼", date: "2026-09-03" }
    ]
  },
  {
    group: "长期通用码",
    codes: [
      { code: "VIP666", reward: "通用新手礼包", date: "" },
      { code: "VIP777", reward: "通用新手礼包", date: "" },
      { code: "VIP888", reward: "通用新手礼包", date: "" },
      { code: "SVIP666", reward: "通用新手礼包", date: "" },
      { code: "FKSSJ666", reward: "通用礼包", date: "" },
      { code: "FKSSJ777", reward: "通用礼包", date: "" },
      { code: "FKSSJ888", reward: "通用礼包", date: "" },
      { code: "水世界666", reward: "通用礼包", date: "" },
      { code: "水世界888", reward: "通用礼包", date: "" },
      { code: "水世界上线礼", reward: "上线纪念礼包", date: "" }
    ]
  },
  {
    group: "TapTap 社区码",
    codes: [
      { code: "wydld666", reward: "TapTap 社区礼包", date: "" },
      { code: "航海冲冲冲", reward: "TapTap 社区礼包", date: "" },
      { code: "J6SSJ5", reward: "TapTap 社区礼包", date: "" },
      { code: "配队有妙招", reward: "TapTap 社区礼包", date: "" },
      { code: "益世界豪礼", reward: "TapTap 社区礼包", date: "" },
      { code: "20wheli", reward: "TapTap 社区礼包", date: "" },
      { code: "末日钓鱼爽", reward: "TapTap 社区礼包", date: "" },
      { code: "海里捞黄金", reward: "TapTap 社区礼包", date: "" },
      { code: "拾荒不慌张", reward: "TapTap 社区礼包", date: "" },
      { code: "开箱拿好礼", reward: "TapTap 社区礼包", date: "" },
      { code: "钓鱼不空军", reward: "TapTap 社区礼包", date: "" },
      { code: "生存水上漂", reward: "TapTap 社区礼包", date: "" },
      { code: "基地超有料", reward: "TapTap 社区礼包", date: "" }
    ]
  },
  {
    group: "微信群礼包码",
    codes: [
      { code: "C45976777666", reward: 微信群礼包", date: "" },
      { code: "9SSJ2N", reward: 微信群礼包", date: "" },
      { code: "LSSJ0M", reward: 微信群礼包", date: "" },
      { code: "SSJ3K7", reward: 微信群礼包", date: "" },
      { code: "2SSJ8C", reward: 微信群礼包", date: "" },
      { code: "X5SSJ9", reward: 微信群礼包", date: "" },
      { code: "BSSJ4F", reward: 微信群礼包", date: "" },
      { code: "SSJ1A", reward: 微信群礼包", date: "" },
      { code: "1SJJ9246", reward: 微信群礼包", date: "" },
      { code: "64SJJ72", reward: 微信群礼包", date: "" },
      { code: "SJJ35190", reward: 微信群礼包", date: "" },
      { code: "SJJ72915", reward: 微信群礼包", date: "" },
      { code: "8SJJ4309", reward: 微信群礼包", date: "" },
      { code: "27SJJ51", reward: 微信群礼包", date: "" },
      { code: "91SJJ37", reward: 微信群礼包", date: "" },
      { code: "5SJJ084", reward: 微信群礼包", date: "" },
      { code: "xc888", reward: 微信群礼包", date: "" },
      { code: "小春888", reward: 微信群礼包", date: "" },
      { code: "ZBZSLBM55", reward: 微信群礼包", date: "" },
      { code: "zbdlb222", reward: 微信群礼包", date: "" },
      { code: "Timo666", reward: 微信群礼包", date: "" },
      { code: "Mozz888", reward: 微信群礼包", date: "" },
      { code: "ZHIB077720W9999", reward: 微信群礼包", date: "" },
      { code: "XQZBDW11", reward: 微信群礼包", date: "" },
      { code: "ZHIBO666", reward: 微信群礼包", date: "" },
      { code: "ZHIBO888", reward: 微信群礼包", date: "" },
      { code: "MJ14789", reward: 微信群礼包", date: "" },
      { code: "SJ78945", reward: 微信群礼包", date: "" },
      { code: "水世界琥珀玩家礼", reward: 微信群礼包", date: "" },
      { code: "FKSSJ666", reward: 微信群礼包", date: "" },
      { code: "xyxz30w666", reward: 微信群礼包", date: "" },
      { code: "SJJ47218", reward: 微信群礼包", date: "" },
      { code: "CYKMP7WY", reward: 微信群礼包", date: "" },
      { code: "yxzP9PKF4E", reward: 微信群礼包", date: "" },
      { code: "APBG6046", reward: 微信群礼包", date: "" },
      { code: "9MPZQHNQ", reward: 微信群礼包", date: "" },
      { code: "0SJJ7429", reward: 微信群礼包", date: "" },
      { code: "UGWSXJG6", reward: 微信群礼包", date: "" },
      { code: "X2U0Y1GE", reward: 微信群礼包", date: "" },
      { code: "yXz29TVQW2", reward: 微信群礼包", date: "" },
      { code: "SSJ88999", reward: 微信群礼包", date: "" },
      { code: "18SJJ53", reward: 微信群礼包", date: "" },
      { code: "VXY2CKO2", reward: 微信群礼包", date: "" },
      { code: "xyxz20w666", reward: 微信群礼包", date: "" },
      { code: "xc666", reward: 微信群礼包", date: "" },
      { code: "小春666", reward: 微信群礼包", date: "" },
      { code: "小春999", reward: 微信群礼包", date: "" },
      { code: "2IQCXVVC", reward: 微信群礼包", date: "" },
      { code: "ZBJFL777", reward: 微信群礼包", date: "" },
      { code: "JSCJQ111", reward: 微信群礼包", date: "" },
      { code: "ckjq065", reward: 微信群礼包", date: "" },
      { code: "Timo777", reward: 微信群礼包", date: "" },
      { code: "Mozz777", reward: 微信群礼包", date: "" },
      { code: "Mozz666", reward: 微信群礼包", date: "" },
      { code: "DYFKSSJ", reward: 微信群礼包", date: "" },
      { code: "益世界关注礼", reward: 微信群礼包", date: "" },
      { code: "KT23456", reward: 微信群礼包", date: "" },
      { code: "CJNLB77", reward: 微信群礼包", date: "" },
      { code: "zbjxz55", reward: 微信群礼包", date: "" },
      { code: "SW45612", reward: 微信群礼包", date: "" },
      { code: "10wheli", reward: 微信群礼包", date: "" },
      { code: "FK12345", reward: 微信群礼包", date: "" },
      { code: "SVIP666", reward: 微信群礼包", date: "" },
      { code: "PSSJ5Q", reward: 微信群礼包", date: "" },
      { code: "SSJ0H8", reward: 微信群礼包", date: "" },
      { code: "SSJ3H5", reward: 微信群礼包", date: "" },
      { code: "6SSJD9", reward: 微信群礼包", date: "" },
      { code: "SSJ2YW", reward: 微信群礼包", date: "" },
      { code: "O7L5J5", reward: 微信群礼包", date: "" },
      { code: "MIYALOVEU", reward: 微信群礼包", date: "" },
      { code: "FKSSJ888", reward: 微信群礼包", date: "" },
      { code: "FKSSJ777", reward: 微信群礼包", date: "" },
      { code: "VIP888", reward: 微信群礼包", date: "" },
      { code: "VIP777", reward: 微信群礼包", date: "" },
      { code: "水世界上线礼", reward: 微信群礼包", date: "" },
      { code: "XO1WM6", reward: 微信群礼包", date: "" },
      { code: "6160P4", reward: 微信群礼包", date: "" },
      { code: "N1040V", reward: 微信群礼包", date: "" },
      { code: "5SSJ9L", reward: 微信群礼包", date: "" },
      { code: "FSSJ1M", reward: 微信群礼包", date: "" },
      { code: "USSJ8W", reward: 微信群礼包", date: "" },
      { code: "SSJ6G4", reward: 微信群礼包", date: "" },
      { code: "7SSJF2", reward: 微信群礼包", date: "" },
      { code: "3SSJK0", reward: 微信群礼包", date: "" },
      { code: "M8SSJ3", reward: 微信群礼包", date: "" },
      { code: "CSSJ5Z", reward: 微信群礼包", date: "" },
      { code: "SSJ7V1", reward: 微信群礼包", date: "" },
      { code: "4TSSJ6", reward: 微信群礼包", date: "" },
      { code: "SSJR8P", reward: 微信群礼包", date: "" },
      { code: "10WDHM", reward: 微信群礼包", date: "" },
    ]
  }
];
